# Generated by Django 4.1.6 on 2023-02-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('episodes', '0004_remove_comment_blog_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='profile.profile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
