# Generated by Django 4.1.6 on 2023-02-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0005_alter_comment_author_alter_episode_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
