# Generated by Django 4.1.6 on 2023-02-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
